version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: celestial
      MYSQL_DATABASE: celestial_probe
      MYSQL_USER: celestial
      MYSQL_PASSWORD: probe123
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql