spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore_tests?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
#      # JPA OPTIONS:
#      # none         = ?
#      # update       = increment DB
#      # validate     = ?
#      # create-drop  = reset/create and drops DB when SeessionFactory closes
#      # ref.: https://docs.spring.io/spring-boot/docs/1.1.0.M1/reference/html/howto-database-initialization.html
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  jackson:
#    serialization:
#      write_dates_as_timestamps: false