package br.com.tiagopedroso.moonprobe.infra.exception;

/**
 * Class imported from https://github.com/supertsp/livraria-online-api
 */

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import org.springframework.http.HttpStatus;

import javax.servlet.http.HttpServletRequest;
import java.time.LocalDateTime;
import java.util.Arrays;

/**
 * Defines an error model based on the IETF specification RFC 787
 * (https://datatracker.ietf.org/doc/html/rfc7807)
 *
 * @author Tiago Penha Pedroso
 */
@Getter
@Setter
@JsonIgnoreProperties({ "cause", "localizedMessage", "message", "stackTrace", "suppressed"})
public abstract class RestErrorException extends RuntimeException {

    private static final long serialVersionUID = 6080367934703451522L;

    protected String status = "KO";

    /**
     * The HTTP status code generated by the origin server
     * for this occurrence of the problem.
     * Note: the original name is status
     */
    protected int statusCode;

    /**
     * A URI that identifies the problem type.
     * It provide human-readable documentation for the problem type.
     * When this member is not present, its value is assumed
     * to be "about:blank". Example: https://www.myapi.com/age-less-than-zero
     */
    protected String type = "about:blank";

    /**
     * A short, human-readable summary of the problem type
     */
    protected String title;

    /**
     * A human-readable explanation specific to this occurrence of the problem
     */
    protected String detail;

    /**
     * The URI of the resource that triggered the error.
     * (Extra attribute not related to RFC 787, which replaces the instance attribute)
     */
    protected String path;

    /**
     * Date and time of occurrence. (Extra attribute not related to RFC 787)
     */
    protected LocalDateTime timestamp;

    public RestErrorException() {
        super("Generic RestErrorException!");
        this.statusCode = HttpStatus.INTERNAL_SERVER_ERROR.value();
        this.title = "Generic RestErrorException!";
        this.timestamp = LocalDateTime.now();
    }

    public RestErrorException(int httpStatus, Object title) {
        super(String.valueOf(title));
        this.statusCode = httpStatus;
        this.title = title == null ? "" : title.toString();
        this.timestamp = LocalDateTime.now();
    }

    public RestErrorException(int httpStatus, Object title, String path) {
        this(httpStatus, title);
        this.path = path;
    }

    public RestErrorException(int httpStatus, Object title, HttpServletRequest request) {
        this(httpStatus, title);
        this.path = request == null ? null : request.getRequestURI();
    }

    public RestErrorException(HttpStatus httpStatus, Object title, String path) {
        this(httpStatus.value(), title, path);
    }

    public RestErrorException(HttpStatus httpStatus, Object title, HttpServletRequest request) {
        this(httpStatus.value(), title, request);
    }

    public RestErrorException(int httpStatus, Object title, Object detail, String path) {
        this(httpStatus, title, path);
        this.detail = validateDetail(detail);
    }

    public RestErrorException(int httpStatus, Object title, Object detail, HttpServletRequest request) {
        this(httpStatus, title, request);
        this.detail = validateDetail(detail);
    }

    public RestErrorException(HttpStatus httpStatus, Object title, Object detail, String path) {
        this(httpStatus, title, path);
        this.detail = validateDetail(detail);
    }

    public RestErrorException(HttpStatus httpStatus, Object title, Object detail, HttpServletRequest request) {
        this(httpStatus, title, request);
        this.detail = validateDetail(detail);
    }

    private String validateDetail(Object detail) {
        if (detail != null) {
            if (detail instanceof RestErrorException) {
                return  ((RestErrorException) detail).getDetail();
            }else if (detail instanceof Exception) {
                return  ((Exception) detail).getMessage();
            } else {
                return detail.toString();
            }
        }

        return "";
    }

    @Override
    public String toString() {
        var list = Arrays.asList(super.getStackTrace());

        return "RestErrorException {"
                + "\n  \"status\": \"" + status + "\", "
                + "\n  \"statusCode\": " + statusCode + ", "
                + "\n  \"type\": \"" + type + "\", "
                + "\n  \"title\": \"" + title + "\", "
                + "\n  \"detail\": \"" + detail + "\", "
                + "\n  \"path\": \"" + path + "\", "
                + "\n  \"timestamp\": \"" + timestamp + "\", "
                + "\n  \"message\": \"" + super.getMessage() + "\", "
                + "\n  \"localizedMessage\": \"" + super.getLocalizedMessage() + "\", "
                + "\n  \"cause\": \"" + super.getCause() + "\", "
                + "\n  \"stackTrace\": \"" + list + "\" "
                +"\n}";
    }
}
